name: Check

on:
  push:
    branches: main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 17.x]
      fail-fast: false
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # v2.2.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # v2.5.1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Node.js deps
        run: npm i
      - name: Install playwright
        run: |
          npx playwright install
          npx playwright install-deps
          npx playwright install-deps chromium
      - name: Run tests
        run: npm run test:e2e
